import "./globals.css";
import { Kanit } from "next/font/google";
import Navbar from "./components/Navbar";
import MyProfilePic from "./components/MyProfilePic";

const kanit = Kanit({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "PNCH Portfolio",
  description: "My portfolio Generated by Next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Navbar />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
